worlds:
  # first world is the default - target of /resource
  # the friendly name of the world - used as the argument in /resource
  overworld:
    # the name of the corresponding world file
    world: resource
    # can be NORMAL, NETHER, or THE_END
    # (or CUSTOM but don't use that)
    type: NORMAL
    # world border size
    # this is a DIAMETER
    size: 5000
  nether:
    world: resource_nether
    type: NETHER
    size: 5000
  end:
    world: resource_the_end
    type: THE_END
    size: 5000
disallowedCommands:
- /sethome
resetIntervalHours: 72
gamerules:
  keepInventory: true
